const introductions = [
  'Great news!',
  'Update:',
  'Just in!',
  "We're thrilled to announce",
  'Exciting development:',
  'Heartwarming moment:',
  'Important alert:',
  'Community reminder:',
  "Don't forget:",
  'Special highlight:',
  'Wonderful news from us!',
  'Big update coming your way!',
  "Today's amazing update!",
  'Thrilled to share:',
  'Exciting news update:',
  'Touching update from our team:',
  'Announcement:',
  'Reminder for everyone:',
  'Special news update:',
  'A heartwarming update:',
  'Community news:',
  'Can’t wait to share this:',
  'Happening now:',
  'From our heart to yours:',
  'Message from our team:',
  'A quick update:',
  'Special community news:',
  'Today’s reminder:',
  'Breaking news!',
  'Here’s what you need to know:',
];
const events = [
  'our annual fundraiser this Saturday!',
  'a pet adoption day this Sunday!',
  'volunteer orientation next week!',
  'our big sale on pet supplies!',
  'a free veterinary check-up camp!',
  'a charity auction for our furry friends!',
  'a community pet parade!',
  'a training session for new pet owners!',
  'an online webinar on pet care!',
  'a meet and greet with our rescues!',
  'a gala event for our donors!',
  'a local community cleanup day!',
  'a photo contest for your pets!',
  'an educational tour of our facilities!',
  'a workshop on pet first aid!',
  'a storytelling evening about rescued pets!',
  'a puppy training class!',
  'a cat socialization event!',
  'a pet-themed art exhibition!',
  'a fundraising walkathon!',
  'our shelter’s anniversary celebration!',
  'a guided tour for potential volunteers!',
  'an animal behavior workshop!',
  'a holiday-themed adoption day!',
  'a summer picnic with the pets!',
  'a foster care information session!',
  'a special movie night fundraiser!',
  'a book sale for pet lovers!',
  'an awareness campaign about spaying and neutering!',
  'our end-of-year donor banquet!',
];
const callsToAction = [
  'Join us and make a difference!',
  'Come see us at the shelter!',
  "Don't miss out on the fun!",
  'Help us spread the word!',
  'Volunteer with us this weekend!',
  'Every donation counts, big or small!',
  'Adopt, don’t shop!',
  'Visit our website for more details!',
  'Follow us on social media!',
  'Sign up for our newsletter!',
  'Share this post with your friends!',
  'Donate today and save a life!',
  'Your support is crucial!',
  'Become a foster parent today!',
  'Consider volunteering your time!',
  'Help us reach our fundraising goal!',
  'Shop our charity merchandise!',
  'Participate in our upcoming event!',
  'Tell your friends about our mission!',
  'Become a member of our society!',
  'Sponsor a pet’s care!',
  'Buy tickets for our next event!',
  'Get involved in our community!',
  'Support our latest campaign!',
  'Check out our new blog post!',
  'Spread the word about our work!',
  'Take a moment to visit our shelter!',
  'Engage with us online!',
  'Stay tuned for more updates!',
  'Remember to care for your pets!',
];
